### ISSUE TITLE
Preview shows blog posts, but does not display the actual post

### ISSUE THREAD

**Issue by doctordns** [planetpowershell/planetpowershell#248] opened 2020-01-09 16:24 UTC

**Comment by doctordns** [comment] 2020-01-09 17:04
If I look at the /Preview page on the main site to see a list of blog posts - I get a nice list, which shows a potentially interesting post: 

![2020-01-09_16-21-24](https://user-images.githubusercontent.com/3630329/72088337-dcc36c00-3301-11ea-990a-57989d0b2a05.png)

So naturally, I click on the View Original Post (it really should be "View Post") I see this:

![2020-01-09_16-22-10](https://user-images.githubusercontent.com/3630329/72088385-f5cc1d00-3301-11ea-9f09-247099949c5b.png)

Not very helpful. Can't you just bring up the actual post>

**Comment by kjacobsen** [comment] 2020-01-12 11:26
This is often caused by ATOM feed and not RSS 2.0 feeds. I have updated PR #246 to use the RSS feed, hopefully that resolves the issue.

**Comment by doctordns** [comment] 2020-01-12 11:34
This appears to now be resolved!

**Comment by doctordns** [comment] 2020-01-12 19:34
I spoke too soon. 

In the source file, I have my blog URI set as: ("https://tfl09.blogspot.com/feeds/posts/default/")

However, if you navigate to https://www.planetpowershell.com/preview - as I write this, the top post is mine but it has no title. 
And if you click on View Original Post, I get sent to: https://tfl09.blogspot.com/feeds/8255810561712404572/comments/default  which is not correct.

Also, my blog feed is Atom. Shouldn't the page look at the XML to see what format this blog post is in and react accordingly. If my blog produces ATOM and yours is RSS, I'd like to see both.

**Comment by kjacobsen** [comment] 2020-01-13 11:20
Hey @doctordns,

Blogspot support both Atom and RSS, so you just need to know which feed to ask for it, hence the tweak in the PR of the feed address.

I just merged the PR, so waiting for build/release to run, and will then check the preview.

**Comment by doctordns** [comment] 2020-01-13 11:21
Ahh - I see.

We'll see what happens when the site rebuilds...

**Comment by kjacobsen** [comment] 2020-01-13 11:34
Link works...but no title for your post?? So weird! Let me keep digging.

**Comment by kjacobsen** [comment] 2020-01-13 11:39
When I navigate to your latest post, no title is displayed there either?

**Comment by doctordns** [comment] 2020-01-13 11:42
Right - the title not showing is my bad  - it's now fixed.

And my post is now showing properly.

**Closed as completed** 2020-01-13 11:53 UTC
